version: '3'

services:
  api: 
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  db: 
    image: mysql
    ports: 
      - 3306:3306
    container_name: mysql_1.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234